### ISSUE TITLE
简单购物车

### ISSUE THREAD

**Issue by happypeter** [happypeter/dj-demos#14]
![cart-simple](https://user-images.githubusercontent.com/72467/30472900-e0c4fa88-9a30-11e7-8fed-508c620e640c.png)

**Comment by happypeter** [comment]
要求：

- 购物区一个商品添加到购物车之后，按钮应该被 disable （禁用）。
- 购物车中能修改每种商品的数量，并运算出总价格

**Comment by happypeter** [comment]
纯前端 state 实现即可，不需要使用 json-sever

**Comment by happypeter** [comment]
更多购物车相关功能，http://yummy-client.haoduoshipin.com/profile

**Comment by guyanguyunan** [comment]
https://guyanguyunan.github.io/dangao/

**Comment by guyanguyunan** [comment]
https://guyanguyunan.github.io/dangao/  徐海南

**Comment by jianghanyue** [comment]
https://jianghanyue.github.io/shopping/ 崔振

**Comment by lunahesal** [comment]
梁杰同学
https://lunahesal.github.io/buycar/

**Comment by beginner-g** [comment]
郭帅
https://beginner-g.github.io/shop/

**Comment by zhuangzz** [comment]
张楠tall
https://zhuangzz.github.io/shopcar/

**Comment by derams** [comment]
赵博英
http://derams.github.io/shunzhi

**Comment by magic-CMR** [comment]
蔡明燃
https://magic-cmr.github.io/shopping-c/

**Comment by lichengcheng123** [comment]
李程程
https://lichengcheng123.github.io/shop/

**Comment by new-happy** [comment]
申建强
https://new-happy.github.io/some-deom/
