### ISSUE TITLE
JSX closing tag error

### ISSUE THREAD

**Issue by angel-geyuwen** [happypeter/dj-demos#6]
![20170907104710](https://user-images.githubusercontent.com/31403252/30143903-9d4c8ed4-9377-11e7-87ba-233afa4c40a9.png)

**Comment by happypeter** [comment]
上面的问题是由于 JSX 标签没有闭合造成的。

```
Syntax error: Expected corresponding tag for <Logo>
```

翻译：语法错误，期望 `<Logo>` 有自己的闭合标签


解决方法:

写成这样即可

```
<Logo  />
```

也就是最后添加上 `/'
